version: "3"

services:
  api:
    image: node:14
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="nest"
    ports:
      - 27017:27017